<?php
// $Id$
/**
 * @file
 * CCK Field support for the WYSIWYG module.
 */

/**
 * Implements hook_init().
 */
function wysiwyg_fields_init() {
  foreach (module_list() as $module) {
    if (file_exists($file = dirname(__FILE__) . "/modules/{$module}.inc")) {
      require_once $file;
    }
  }

  // Enable wysiwyg plugins.
  foreach (content_fields() as $field) {
    if ($field['widget']['wysiwyg_fields_status']) {
      foreach (wysiwyg_profile_load_all() as $profile) {
        $profile->settings = is_array($profile->settings) ? $profile->settings : array();
        $profile->settings['buttons'] = is_array($profile->settings['buttons']) ? $profile->settings['buttons'] : array();

        $id = "wysiwyg_fields_{$field['field_name']}";
        if (!isset($profile->settings['buttons']['drupal'][$id]) || empty($profile->settings['buttons']['drupal'][$id])) {
          $profile->settings['buttons']['drupal'][$id] = 1;
          db_query("UPDATE {wysiwyg} SET settings = '%s' WHERE format = %d", serialize($profile->settings), $profile->format);
        }
      }
    }
  }
}

/**
 * Implements hook_menu().
 */
function wysiwyg_fields_menu() {
  $items = array();

  $items['ahah/wysiwyg_fields'] = array(
    'title' => 'Wysiwyg Fields AHAH callback',
    'page callback' => 'wysiwyg_fields_ahah',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items[drupal_get_path('module', 'wysiwyg_fields') . '/plugins'] = array(
    'title' => 'Wysiwyg Fields dynamic Wysiwyg plugin js',
    'page callback' => 'wysiwyg_fields_wysiwyg_plugin_js',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_wysiwyg_fields_elements_alter().
 */
function wysiwyg_fields_wysiwyg_fields_elements_alter(&$elements) {
  foreach (module_invoke_all('widget_info') as $widget_type => $widget) {
    $elements[$widget_type] = is_array($elements[$widget_type]) ? $elements[$widget_type] : array();
    $elements[$widget_type]['#process'] = is_array($elements[$widget_type]['#process']) ? $elements[$widget_type]['#process'] : array();
    $elements[$widget_type]['#process'][] = 'wysiwyg_fields_elements_process';
  }
}

/**
 * Implements hook_theme().
 */
function wysiwyg_fields_theme() {
  $items = array();
  $path = drupal_get_path('module', 'wysiwyg_fields') . '/templates';

  $items['wysiwyg_fields_wysiwyg_plugin_js'] = array(
    'arguments' => array(
      'field' => NULL,
    ),
    'template' => 'wysiwyg_fields_wysiwyg_plugin_js',
    'path' => $path,
  );

  return $items;
}

/**
 * Implements hook_theme_registry_alter().
 */
function wysiwyg_fields_theme_registry_alter(&$theme_registry) {
  foreach (module_list() as $module) {
    $function = "{$module}_wysiwyg_fields_theme_bypass";
    if (is_array(module_invoke($module, 'widget_info'))) {
      foreach (module_invoke($module, 'widget_info') as $widget_type => $widget) {
        if (isset($theme_registry[$widget_type]) && ((function_exists($function) && !$function($widget_type)) || !function_exists($function))) {
          $theme_registry[$widget_type]['function'] = 'theme_wysiwyg_fields_element';
        }
      }
    }
  }
}

/**
 * Implements hook_wysiwyg_fields_nodeapi_alter().
 */
function wysiwyg_fields_wysiwyg_fields_nodeapi_alter(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'prepare':
    case 'validate':
      $tokens = array();
      $textfields = _wysiwyg_fields_textfields($node);
      foreach ($textfields as &$textfield) {
        $tokens = array_merge(_wysiwyg_fields_text_to_tokens($textfield['value']), $tokens);
      }

      $replacements = array();
      $delta = array();
      foreach ($tokens as $token) {
        $replacements[$token[0]] = _wysiwyg_fields_filter_process($node, $token[0]);
        $delta[$token[1]] = isset($delta[$token[1]]) ? $delta[$token[1]] : 0;
        $delta[$token[1]] = $token[2] + 1 > $delta[$token[1]] ? $token[2] + 1 : $delta[$token[1]];
      }

      $fields = array();
      foreach (content_fields(NULL, $node->type) as $field) {
        $fields[$field['field_name']] = array(
          'multiple' => $field['multiple'],
          'delta' => isset($delta[$field['field_name']]) ? $delta[$field['field_name']] : 0,
        );
      }

      // Convert settings to JavaScript for Wysiwyg plugin.
      drupal_add_js(
        array(
          'wysiwygFields' => array(
            'fields' => $fields,
            'replacements' => $replacements
          )
        ),
        'setting'
      );
      break;
  }
}

/**
 * Implements hook_wysiwyg_fields_form_alter_alter().
 */
function wysiwyg_fields_wysiwyg_fields_form_alter_alter(&$form, &$form_state, $form_id) {
  if (isset($form['type']['#value']) && $form_id == "{$form['type']['#value']}_node_form") {
    $form['#after_build'][] = 'wysiwyg_fields_form_alter_build_after';
  }
}

/**
 *
 */
function wysiwyg_fields_elements_process($form_element) {
  $field = content_fields($form_element['#field_name'], $form_element['#type_name']);

  if ($form_element['#type'] == $field['widget']['type'] && isset($field['widget']['wysiwyg_fields_status']) && $field['widget']['wysiwyg_fields_status'] == TRUE) {
    $form_element['#element_validate'][] = 'wysiwyg_fields_element_validate';

    // AHAH Wrapper.
    $prefix = "<div id='{$form_element['#id']}-wysiwyg-fields-ahah-wrapper' class='wysiwyg_fields-field wysiwyg_fields-{$form_element['#field_name']}-field'>";
    $form_element['#prefix'] = isset($form_element['#prefix']) ? "{$prefix}{$form_element['#prefix']}" : $prefix;
    $form_element['#suffix'] = isset($form_element['#suffix']) ? "{$form_element['#suffix']}</div>" : '</div>';

    $form_element['wysiwyg_fields'] = array(
      '#prefix' => '<div class="wysiwyg_fields-widget">',
      '#suffix' => '</div>',
      '#weight' => 200,
    );

    // Formatters.
    $formatters = array();
    foreach ($field['widget']['wysiwyg_fields_formatters'] as $delta => $formatter) {
      $formatter = _content_get_formatter($formatter, $field['type']);
      $formatters["{$formatter[module]}_formatter_{$delta}"] = $formatter['label'];
    }

    // Multiple formatters - select field.
    if (count($field['widget']['wysiwyg_fields_formatters']) > 1) {
      $form_element['wysiwyg_fields']['wysiwyg_fields_formatters'] = array(
        '#type' => 'select',
        '#options' => $formatters,
        '#name' => "{$form_element['#name']}[wysiwyg_fields_formatters]",
        '#id' => "{$form_element['#id']}-wysiwyg-fields-formatters",
        '#attributes' => array(
          'class' => 'wysiwyg_fields_formatters',
        ),
      );
    }

    // Single formatter - hidden field.
    else {
      $form_element['wysiwyg_fields']['wysiwyg_fields_formatters'] = array(
        '#type' => 'hidden',
        '#value' => array_shift(array_keys($formatters)),
        '#name' => "{$form_element['#name']}[wysiwyg_fields_formatters]",
        '#id' => "{$form_element['#id']}-wysiwyg-fields-formatters",
      );
    }

    // Insert button.
    $form_element['wysiwyg_fields']['wysiwyg_fields_insert'] = array(
      '#type' => 'submit',
      '#value' => t('Insert'),
      '#ahah' => array(
        'path' => "ahah/wysiwyg_fields/insert/{$form_element['#field_name']}/{$form_element['#delta']}",
        'wrapper' => "{$form_element['#id']}-wysiwyg-fields-ahah-wrapper",
      ),
      '#name' => "{$form_element['#name']}[wysiwyg_fields_insert]",
      '#id' => "{$form_element['#id']}-wysiwyg-fields-insert",
      '#attributes' => array(
        'class' => 'wysiwyg_fields_insert',
      ),
    );
  }

  return $form_element;
}

/**
 *
 */
function wysiwyg_fields_element_validate($element, &$form_state) {
  if (!empty($form_state['values'][$element['#field_name']])) {
    foreach ($form_state['values'][$element['#field_name']] as $delta => &$field) {
      if (is_array($field) && empty($field['wysiwyg_fields']['wysiwyg_fields_formatters']) && is_array($form_state['post'][$element['#field_name']][$delta])) {
        array_walk_recursive($form_state['post'][$element['#field_name']][$delta], '_wysiwyg_fields_element_validate', &$field['wysiwyg_fields']['wysiwyg_fields_formatters']);
      }
    }
  }
}

/**
 *
 */
function _wysiwyg_fields_element_validate($item, $key, $formatter) {
  if ($key == 'wysiwyg_fields_formatters') {
    $formatter = $item;
  }
}

/**
 *
 */
function wysiwyg_fields_form_alter_build_after($form_element, &$form_state) {
  // Store Content Type in $_SESSION['wysiwyg_fields'] to provide context.
  $_SESSION['wysiwyg_fields'] = $form_element['type']['#value'];

  foreach (content_fields(NULL, $form_element['type']['#value']) as $field) {
    if (isset($field['widget']['wysiwyg_fields_status']) && $field['widget']['wysiwyg_fields_status']) {
      // Modify field element.
      $form_element[$field['field_name']]['#prefix'] = "<div id='wysiwyg_fields-{$field['field_name']}-wrapper'>{$form_element[$field['field_name']]['#prefix']}";
      $form_element[$field['field_name']]['#suffix'] = "{$form_element[$field['field_name']]['#suffix']}</div>";

      // Add javascript.
      jquery_ui_add(array('ui.core', 'ui.dialog'));
      drupal_add_js(drupal_get_path('module', 'wysiwyg_fields') . '/js/wysiwyg_fields.js');

      // @TODO - Move this to modules/wysiwyg.inc
      foreach (wysiwyg_profile_load_all() as $profile) {
        // @TODO - Check if file exists.
        drupal_add_js(drupal_get_path('module', 'wysiwyg_fields') . "/js/wysiwyg.{$profile->editor}.js");
      }

      // Add Style sheets.
      drupal_add_css(drupal_get_path('module', 'wysiwyg_fields') . '/wysiwyg_fields.css');

      // jQuery 1.7 theme.
      if (file_exists($css = drupal_get_path('module', 'jquery_ui') . '/jquery.ui/themes/base/ui.all.css')) {
        // @TODO - Change if #388384 ever gets resolved.
        drupal_add_css($css);
      }

      // jQuery 1.6 theme.
      else if (file_exists($css = drupal_get_path('module', 'jquery_ui') . '/jquery.ui/themes/default/ui.all.css')) {
        drupal_add_css($css);
      }

      else {
        // @TODO - Move this to hook_requirements?
        drupal_set_message(t('No jQuery UI theme found, please download the appropriate files from: !url', array('!url' => l('http://blog.jqueryui.com/2010/02/jquery-ui-download-builderthemeroller-status/', 'http://blog.jqueryui.com/2010/02/jquery-ui-download-builderthemeroller-status/'))), 'warning');
      }

    }
  }

  return $form_element;
}

/**
 * Page callback; Wysiwyg Fields AHAH.
 */
function wysiwyg_fields_ahah() {
  // Immediately disable devel shutdown functions so that it doesn't botch our
  // JSON output.
  $GLOBALS['devel_shutdown'] = FALSE;

  if (empty($_POST['form_build_id'])) {
    // Invalid request.
    drupal_set_message(t('An unrecoverable error occurred.'));
    print drupal_to_js(array('data' => theme('status_messages')));
    exit;
  }

  // Invoke wysiwyg_fields_ahah_OP().
  $op = arg(2);
  if (!empty($op)) {
    $function = "wysiwyg_fields_ahah_{$op}";
    print drupal_to_js($function());
  }

  else {
    // Invalid request.
    drupal_set_message(t('An unrecoverable error occurred.'));
    print drupal_to_js(array('data' => theme('status_messages')));
    exit;
  }
}

/**
 * @TODO - Weight field becomes visible after AHAH - fix.
 * @TODO - Formatter changes.
 */
function wysiwyg_fields_ahah_insert() {
  // Include node definition.
  module_load_include('inc', 'node', 'node.pages');

  // Load the form.
  $form_state = array(
    'rebuild' => TRUE,
    'storage' => NULL,
    'submitted' => FALSE
  );
  $form_build_id = $_POST['form_build_id'];
  $form = form_get_cache($form_build_id, $form_state);
  $args = $form['#parameters'];
  $form_id = array_shift($args);
  $form_state['post'] = $form['#post'] = $_POST;
  $form['#programmed'] = $form['#redirect'] = FALSE;

  // Process the form with drupal_process_form(), which calls the submit
  // handlers that puts whatever was worthy of keeping in the $form_state.
  drupal_process_form($form_id, $form, $form_state);

  // Session messages would get displayed at the next regular request, but
  // we're in AHAH here, so that won't happen. Make them go away.
  unset($_SESSION['messages']);

  $output = drupal_render($form[arg(3)][arg(4)]);
  $errors = form_get_errors();
  $item = $form_state['values'][arg(3)][arg(4)];
  if (isset($errors) && (isset($errors[$item['_error_element']]) || isset($errors[arg(3)]))) {
    $error = isset($errors[$item['_error_element']]) ? $errors[$item['_error_element']] : $errors[arg(3)];
    drupal_set_message($error, 'error');
    $output = theme('status_messages') . $output;
  }

  else {
    $field = content_fields(arg(3));
    $formatter = explode('_formatter_', $item['wysiwyg_fields']['wysiwyg_fields_formatters']);
    $element = _wysiwyg_fields_ahah_get_element($field, $item, $formatter);

    // @TODO - Turn this into a theme function?
    $id = 'wysiwyg_fields-' . arg(3) . '-' . arg(4) . "-{$item['wysiwyg_fields']['wysiwyg_fields_formatters']}";
    $element = drupal_to_js("
      <div id='{$id}' class='wysiwyg_fields wysiwyg_fields-" . arg(3) . "'>
        " . theme($element['#theme'], $element) . "
      </div>");
    $output .= "
      <script type='text/javascript'>
        Drupal.wysiwyg.instances[Drupal.wysiwyg.activeId].insert({$element});
        $('#wysiwyg_fields-" . arg(3) . "-wrapper').dialog('close');
        Drupal.wysiwygFields.deltaUpdate('" . arg(3) . "', " . arg(4) . ");
        if (typeof Drupal.settings.wysiwygFields.fields." . arg(3) . ".active == 'undefined') {
          $('.form-submit[name=\"" . arg(3) . "_add_more\"]').trigger('mousedown');
        }
      </script>";
  }

  return array(
    'status' => TRUE,
    'data' => $output,
  );
}

/**
 *
 */
function _wysiwyg_fields_ahah_get_element($field, $item, $formatter) {
  if (function_exists($function = "{$field['module']}_field")) {
  //  // Invoke hook_field('load').
  //  $items = $function('load', $node = array(), $field, $items = array($item), FALSE, FALSE);
  //  $item = isset($items[arg(3)][0]) ? $items[arg(3)][0] : $item;
  //
    // Invoke hook_field('sanitize').
    $items = array(&$item);
    $function('sanitize', $node = array(), $field, $items, FALSE, FALSE);
  }

  $element = array(
    '#formatter' => $formatter[1],
    '#node' => array(), // @TODO - Fix this
    '#type_name' => $field['type_name'],
    '#field_name' => $field['field_name'],
    '#weight' => 0, // @TODO - Fix this
    '#theme' => "{$formatter[0]}_formatter_{$formatter[1]}",
    '#item' => $item,
    '#title' => '', // @TODO - Fix this
    '#description' => '', // @TODO - Fix this
  );

  return $element;
}

/**
 * Page callback; Render dynamic Wysiwyg plugin js.
 */
function wysiwyg_fields_wysiwyg_plugin_js() {
  $request = explode('/', request_uri());
  $field = drupal_substr($request[count($request) - 2], 15);

  header("Content-type: text/javascript");
  print theme('wysiwyg_fields_wysiwyg_plugin_js', $field);
}

/**
 *
 */
function theme_wysiwyg_fields_element($element) {
  // @TODO - This likely bypasses theme overides. Test, confirm and fix.
  if (!isset($element['wysiwyg_fields']) && function_exists($function = "theme_{$element['#type']}")) {
    return $function($element);
  }
  return $element['#children'];
}
