<?php
// $Id$
/**
 * @file
 * CCK Field support for the WYSIWYG module.
 */

/**
 * Implements hook_init().
 */
function wysiwyg_fields_init() {
  foreach (module_list() as $module) {
    if (file_exists($file = dirname(__FILE__) . "/includes/{$module}.inc")) {
      require_once $file;
    }
  }

  drupal_alter('wysiwyg_fields_init', $data = NULL);
}

/**
 * Implements hook_wysiwyg_fields_menu_alter().
 */
function wysiwyg_fields_wysiwyg_fields_menu_alter(&$items) {
  $items['ahah/wysiwyg_fields'] = array(
    'title' => 'Wysiwyg Fields AHAH callback',
    'page callback' => 'wysiwyg_fields_ahah',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
}

/**
 * Implements hook_wysiwyg_fields_elements_alter().
 */
function wysiwyg_fields_wysiwyg_fields_elements_alter(&$elements) {
  foreach (module_invoke_all('widget_info') as $widget_type => $widget) {
    $elements[$widget_type] = is_array($elements[$widget_type]) ? $elements[$widget_type] : array();
    $elements[$widget_type]['#process'] = is_array($elements[$widget_type]['#process']) ? $elements[$widget_type]['#process'] : array();
    $elements[$widget_type]['#process'][] = 'wysiwyg_fields_elements_process';
  }
}

/**
 * Implements hook_wysiwyg_fields_theme_alter().
 */
function wysiwyg_fields_wysiwyg_fields_theme_alter(&$items) {
  $path = drupal_get_path('module', 'wysiwyg_fields') . '/templates';

  // @TODO - Move to wysiwyg.inc.
  $items['wysiwyg_fields_wysiwyg_plugin_js'] = array(
    'arguments' => array(
      'field' => NULL,
    ),
    'template' => 'wysiwyg_fields_wysiwyg_plugin_js',
    'path' => $path,
  );
}

/**
 * Implements hook_theme_registry_alter().
 */
function wysiwyg_fields_theme_registry_alter(&$theme_registry) {
  foreach (module_list() as $module) {
    $function = "{$module}_wysiwyg_fields_theme_bypass";
    if (is_array(module_invoke($module, 'widget_info'))) {
      foreach (module_invoke($module, 'widget_info') as $widget_type => $widget) {
        if (isset($theme_registry[$widget_type]) && ((function_exists($function) && !$function($widget_type)) || !function_exists($function))) {
          $theme_registry[$widget_type]['function'] = 'theme_wysiwyg_fields_element';
        }
      }
    }
  }
}

/**
 * Implements hook_wysiwyg_fields_nodeapi_alter().
 */
function wysiwyg_fields_wysiwyg_fields_nodeapi_alter(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'prepare':
    case 'validate':
      $tokens = array();
      $textfields = _wysiwyg_fields_textfields($node);
      foreach ($textfields as &$textfield) {
        $tokens = array_merge(_wysiwyg_fields_text_to_tokens($textfield['value']), $tokens);
      }

      $replacements = array();
      foreach ($tokens as $token) {
        $replacements[$token[0]] = _wysiwyg_fields_filter_process($node, $token[0]);
      }

      $fields = array();
      foreach (content_fields(NULL, $node->type) as $field) {
        // Get first empty delta.
        $delta = NULL;
        $function = "{$field['module']}_content_is_empty";
        if (is_array($node->{$field['field_name']})) {
          foreach ($node->{$field['field_name']} as $count => $item) {
            if ($function($item, $field)) {
              $delta = $count;
              break;
            }
          }
        }

        $fields[$field['field_name']] = array(
          'multiple' => $field['multiple'],
          'delta' => !is_null($delta) ? $delta : count($node->{$field['field_name']}),
        );
      }

      // Convert settings to JavaScript for Wysiwyg plugin.
      drupal_add_js(
        array(
          'wysiwygFields' => array(
            'fields' => $fields,
            'replacements' => $replacements
          )
        ),
        'setting'
      );
      break;
  }
}

/**
 * Implements hook_wysiwyg_fields_form_alter_alter().
 */
function wysiwyg_fields_wysiwyg_fields_form_alter_alter($form, $form_state, $form_id) {
  if (isset($form['type']['#value']) && $form_id == "{$form['type']['#value']}_node_form") {
    // Store Content Type in $_SESSION['wysiwyg_fields'] to provide context.
    $_SESSION['wysiwyg_fields'] = $form['type']['#value'];

    foreach ($form['#field_info'] as $field) {
      if (isset($field['widget']['wysiwyg_fields_status']) && $field['widget']['wysiwyg_fields_status']) {
        // Modify field element.
        $form[$field['field_name']]['#prefix'] = "<div id='wysiwyg_fields-{$field['field_name']}-wrapper'>{$form[$field['field_name']]['#prefix']}";
        $form[$field['field_name']]['#suffix'] = "{$form[$field['field_name']]['#suffix']}</div>";

        // Add javascript.
        jquery_ui_add(array('ui.core', 'ui.dialog'));
        drupal_add_js(drupal_get_path('module', 'wysiwyg_fields') . '/scripts/wysiwyg_fields.js');

        // @TODO - Move this to modules/wysiwyg.inc
        foreach (wysiwyg_profile_load_all() as $profile) {
          if (isset($profile->editor) && file_exists($js = drupal_get_path('module', 'wysiwyg_fields') . "/scripts/wysiwyg.{$profile->editor}.js")) {
            drupal_add_js($js);
          }
        }

        // Add Style sheets.
        drupal_add_css(drupal_get_path('module', 'wysiwyg_fields') . '/styles/node_form.css');

        // jQuery 1.7 theme.
        if (file_exists($css = JQUERY_UI_PATH . '/themes/base/ui.all.css')) {
          // @TODO - Change if #388384 ever gets resolved.
          drupal_add_css($css);
        }

        // jQuery 1.6 theme.
        elseif (file_exists($css = JQUERY_UI_PATH . '/themes/default/ui.all.css')) {
          drupal_add_css($css);
        }

        else {
          // @TODO - Move this to hook_requirements?
          drupal_set_message(t('No jQuery UI theme found, please download the appropriate files from: !url', array('!url' => l('http://blog.jqueryui.com/2010/02/jquery-ui-download-builderthemeroller-status/', 'http://blog.jqueryui.com/2010/02/jquery-ui-download-builderthemeroller-status/'))), 'warning');
        }
      }
    }
  }
}

/**
 *
 */
function wysiwyg_fields_elements_process($form_element) {
  $field = content_fields($form_element['#field_name'], $form_element['#type_name']);

  if ($form_element['#type'] == $field['widget']['type'] && isset($field['widget']['wysiwyg_fields_status']) && $field['widget']['wysiwyg_fields_status'] == TRUE) {
    $form_element['#element_validate'][] = 'wysiwyg_fields_element_validate';

    // AHAH Wrapper.
    $prefix = "<div id='{$form_element['#id']}-wysiwyg-fields-ahah-wrapper' class='wysiwyg_fields-field wysiwyg_fields-{$form_element['#field_name']}-field'>";
    $form_element['#prefix'] = isset($form_element['#prefix']) ? "{$prefix}{$form_element['#prefix']}" : $prefix;
    $form_element['#suffix'] = isset($form_element['#suffix']) ? "{$form_element['#suffix']}</div>" : '</div>';

    $form_element['wysiwyg_fields'] = array(
      '#prefix' => '<div class="wysiwyg_fields-widget">',
      '#suffix' => '</div>',
      '#weight' => 200,
    );

    // Formatters.
    $formatters = array();
    foreach ($field['widget']['wysiwyg_fields_formatters'] as $delta => $formatter) {
      $formatter = _content_get_formatter($formatter, $field['type']);
      $formatters["{$formatter[module]}_formatter_{$delta}"] = $formatter['label'];
    }

    // Multiple formatters - select field.
    if (count($field['widget']['wysiwyg_fields_formatters']) > 1) {
      $form_element['wysiwyg_fields']['wysiwyg_fields_formatters'] = array(
        '#type' => 'select',
        '#options' => $formatters,
        '#name' => "{$form_element['#name']}[wysiwyg_fields_formatters]",
        '#id' => "{$form_element['#id']}-wysiwyg-fields-formatters",
        '#attributes' => array(
          'class' => 'wysiwyg_fields_formatters',
        ),
      );
    }

    // Single formatter - hidden field.
    else {
      $form_element['wysiwyg_fields']['wysiwyg_fields_formatters'] = array(
        '#type' => 'hidden',
        '#value' => array_shift(array_keys($formatters)),
        '#name' => "{$form_element['#name']}[wysiwyg_fields_formatters]",
        '#id' => "{$form_element['#id']}-wysiwyg-fields-formatters",
      );
    }

    // Insert button.
    switch ($field['multiple']) {
      case 0:
        $wrapper = "{$form_element['#id']}-wysiwyg-fields-ahah-wrapper";
        break;
      case 1:
        $wrapper = str_replace('_', '-', $field['field_name']) . '-items';
        break;
      default:
        $wrapper = "{$field['field_name']}_values";
    }
    $form_element['wysiwyg_fields']['wysiwyg_fields_insert'] = array(
      '#type' => 'submit',
      '#value' => t('Insert'),
      '#ahah' => array(
        'path' => "ahah/wysiwyg_fields/insert/{$form_element['#field_name']}/{$form_element['#delta']}",
        'wrapper' => $wrapper,
      ),
      '#name' => "{$form_element['#name']}[wysiwyg_fields_insert]",
      '#id' => "{$form_element['#id']}-wysiwyg-fields-insert",
      '#attributes' => array(
        'class' => 'wysiwyg_fields_insert',
      ),
    );

    // Multiselect checkbox.
    $form_element['wysiwyg_fields']['wysiwyg_fields_select'] = array(
      '#type' => 'checkbox',
      '#defult_value' => FALSE,
      '#name' => "{$form_element['#name']}[wysiwyg_fields_select]",
      '#id' => "{$form_element['#id']}-wysiwyg-fields-select",
      '#attributes' => array(
        'class' => 'wysiwyg_fields_select',
      ),
    );

    // Original field delta.
    $form_element['wysiwyg_fields']['wysiwyg_fields_delta'] = array(
      '#type' => 'hidden',
      '#value' => $form_element['#delta']
    );
  }

  return $form_element;
}

/**
 *
 */
function wysiwyg_fields_element_validate($element, &$form_state) {
  if (!empty($form_state['values'][$element['#field_name']])) {
    foreach ($form_state['values'][$element['#field_name']] as $delta => &$field) {
      if (is_array($field) && empty($field['wysiwyg_fields']['wysiwyg_fields_formatters']) && is_array($form_state['post'][$element['#field_name']][$delta])) {
        array_walk_recursive($form_state['post'][$element['#field_name']][$delta], '_wysiwyg_fields_element_validate', &$field['wysiwyg_fields']['wysiwyg_fields_formatters']);
      }
    }
  }
}

/**
 *
 */
function _wysiwyg_fields_element_validate($item, $key, $formatter) {
  if ($key == 'wysiwyg_fields_formatters') {
    $formatter = $item;
  }
}

/**
 *
 */
function wysiwyg_fields_icons($checksum = NULL, $reset = FALSE) {
  static $icons = array();

  if (!$reset && $cache = cache_get('wysiwyg_fields_icons')) {
    $icons = $cache->data;
  }

  if (count($icons) == 0) {
    $directories = module_invoke_all('wysiwyg_fields_icons');
    foreach ($directories as $directory) {
      if (is_dir($directory)) {
        foreach (scandir($directory) as $file) {
          if (!is_dir($file)) {
            // User MD5 checksum to prevent duplicates.
            $icons[md5_file("{$directory}/{$file}")] = "{$directory}/{$file}";
          }
        }
      }
    }
    cache_set('wysiwyg_fields_icons', $icons);
  }

  return isset($checksum) ? $icons[$checksum] : $icons;
}

/**
 * Page callback; Wysiwyg Fields AHAH.
 */
function wysiwyg_fields_ahah() {
  // Immediately disable devel shutdown functions so that it doesn't botch our
  // JSON output.
  $GLOBALS['devel_shutdown'] = FALSE;

  if (empty($_POST['form_build_id'])) {
    // Invalid request.
    drupal_set_message(t('An unrecoverable error occurred.'));
    print drupal_to_js(array('data' => theme('status_messages')));
    exit;
  }

  // Invoke wysiwyg_fields_ahah_OP().
  $op = arg(2);
  if (!empty($op)) {
    $function = "wysiwyg_fields_ahah_{$op}";
    print drupal_to_js($function());
  }

  else {
    // Invalid request.
    drupal_set_message(t('An unrecoverable error occurred.'));
    print drupal_to_js(array('data' => theme('status_messages')));
    exit;
  }
}

/**
 * @TODO - Weight field becomes visible after AHAH - fix.
 * @TODO - Formatter changes.
 */
function wysiwyg_fields_ahah_insert() {
  // Include node definition.
  module_load_include('inc', 'node', 'node.pages');

  // Load the form.
  $form_state = array(
    'rebuild' => TRUE,
    'storage' => NULL,
    'submitted' => FALSE
  );
  $form_build_id = $_POST['form_build_id'];
  $form = form_get_cache($form_build_id, $form_state);
  $args = $form['#parameters'];
  $form_id = array_shift($args);
  $form_state['post'] = $form['#post'] = $_POST;
  $form['#programmed'] = $form['#redirect'] = FALSE;

  // Process the form with drupal_process_form(), which calls the submit
  // handlers that puts whatever was worthy of keeping in the $form_state.
  drupal_process_form($form_id, $form, $form_state);

  // Session messages would get displayed at the next regular request, but
  // we're in AHAH here, so that won't happen. Make them go away.
  unset($_SESSION['messages']);

  unset($form[arg(3)]['#prefix'], $form[arg(3)]['#suffix']);
  $output = drupal_render($form[arg(3)]);
  $errors = form_get_errors();

  $items = array();
  $deltas = array();
  foreach ($_POST[arg(3)] as $delta => $item) {
    if ($item['wysiwyg_fields_select'] == TRUE) {
      $items[$delta] = $form_state['values'][arg(3)][$delta];
      $deltas[] = $delta;
    }
  }
  $items = count($items) > 0 ? $items : array($form_state['values'][arg(3)][arg(4)]);
  $deltas = count($deltas) > 0 ? $deltas : array(arg(4));

  // Check for empty fields.
  $field = content_fields(arg(3));
  $is_empty = "{$field['module']}_content_is_empty";
  $error = FALSE;
  $message = '';
  foreach ($items as $item) {
    if ($is_empty($item, $field) && empty($errors[$item['_error_element']])) {
      $errors[$item['_error_element']] = t("Can't insert an empty field.");
    }

    if (isset($errors[$item['_error_element']])) {
      $error = TRUE;
      $message .= $errors[$item['_error_element']];
    }
  }

  // @TODO - Add multi-field error checking.
  //$item = $form_state['values'][arg(3)][arg(4)];
  //if (isset($errors) && (isset($errors[$item['_error_element']]) || isset($errors[arg(3)]))) {
  //  $error = isset($errors[$item['_error_element']]) ? $errors[$item['_error_element']] : $errors[arg(3)];
  //  drupal_set_message($error, 'error');
  //  $output = theme('status_messages') . $output;
  //}
  if ($error) {
    drupal_set_message($message, 'error');
    $output = theme('status_messages') . $output;
  }

  else {
    list($formatter_module, $formatter_name) = explode('_formatter_', $items[current(array_keys($items))]['wysiwyg_fields']['wysiwyg_fields_formatters']);
    $formatter = _content_get_formatter($formatter_name, $field['module']);
    $id = 'wysiwyg_fields-' . arg(3) . '-' . implode('_', $deltas) . "-{$items[current(array_keys($items))]['wysiwyg_fields']['wysiwyg_fields_formatters']}";

    if ($formatter->multiple == CONTENT_HANDLE_CORE) {
      $element = '';
      foreach ($items as $item) {
        $item = _wysiwyg_fields_ahah_get_element($field, $item, array($formatter_module, $formatter_name));
        $element .= theme($item['#theme'], $item);
      }
    }
    else {
      $element = _wysiwyg_fields_ahah_get_element($field, $items, array($formatter_module, $formatter_name));
      $element = theme($element['#theme'], $element);
    }
    $element = drupal_to_js("<wrapper_element id='{$id}' class='wysiwyg_fields wysiwyg_fields-" . arg(3) . "'>" . $element . "</wrapper_element>");

    // Get first empty delta.
    $delta = NULL;
    ksort($_POST[arg(3)]);
    foreach ($_POST[arg(3)] as $count => $item) {
      if ($is_empty($item, $field)) {
        $delta = $count;
        break;
      }
    }
    $add_more = is_null($delta);
    $delta = is_null($delta) ? $count + 1 : $delta;

    // Trigger 'Add more' button.
    $add_more = ($field['multiple'] == 1 && $add_more) ? "$('.form-submit[name=\"" . arg(3) . "_add_more\"]').trigger('mousedown');" : '';

    // @TODO - Turn this into a theme function?
    // @TODO - Clean/Improve up this code.
    $output .= "
      <script type='text/javascript'>
        $('#wysiwyg_fields-" . arg(3) . "-wrapper').dialog('close');
        Drupal.wysiwygFields.dialogClose('" . arg(3) . "');
        content = {$element};
        content = content.replace('wrapper_element', Drupal.wysiwygFields.wrapperElement, 'g');
        Drupal.wysiwyg.instances[Drupal.wysiwyg.activeId].insert(content);
        Drupal.settings.wysiwygFields.fields['" . arg(3) . "'].delta = {$delta};
        {$add_more}
      </script>";
  }

  return array(
    'status' => TRUE,
    'data' => $output,
  );
}

/**
 *
 */
function _wysiwyg_fields_ahah_get_element($field, $items, $formatter) {
  if (!is_array(current($items))) {
    $items = array($items);
  }

  if (function_exists($function = "{$field['module']}_field")) {
  //  // Invoke hook_field('load').
  //  $items = $function('load', $node = array(), $field, $items = array($item), FALSE, FALSE);
  //  $item = isset($items[arg(3)][0]) ? $items[arg(3)][0] : $item;
  //
    // Invoke hook_field('sanitize').
    $function('sanitize', $node = array(), $field, $items, FALSE, FALSE);
  }

  foreach ($items as $delta => $item) {
    unset($items[$delta]);
    $items[$delta]['#item'] = $item;
  }

  $element = array_merge(
    array(
      '#formatter' => $formatter[1],
      '#node' => array(), // @TODO - Fix this
      '#type_name' => $field['type_name'],
      '#field_name' => $field['field_name'],
      '#weight' => 0, // @TODO - Fix this
      '#theme' => "{$formatter[0]}_formatter_{$formatter[1]}",
      '#item' => $items[0]['#item'],
      '#title' => '', // @TODO - Fix this
      '#description' => '', // @TODO - Fix this
    ),
    $items
  );

  return $element;
}

/**
 *
 */
function theme_wysiwyg_fields_element($element) {
  // @TODO - This likely bypasses theme overides. Test, confirm and fix.
  if (!isset($element['wysiwyg_fields']) && function_exists($function = "theme_{$element['#type']}")) {
    return $function($element);
  }
  return $element['#children'];
}
